//CREAMOS LA TABLE EMPLEADO

CREATE TABLE EMPLEADO(
CODEMP INT,
NOMBRE VARCHAR2(20),
FEC_NAC DATE,
CARGO VARCHAR2(20),
DIRECCION VARCHAR2(30),
CIUDAD VARCHAR2(20)
);

//INSERTAMOS REGISTROS DENTRO DE ELLAS

INSERT INTO EMPLEADO VALUES(1, 'MARTÍN', '1/1/1990', 'MANTENCIÓN', 'ALMOS 1234', 'SANTIAGO');
INSERT INTO EMPLEADO VALUES(2, 'JOAQUÍN', '3/15/1990', 'ATENCIÓN CLIENTES', 'PINOS 6542', 'SANTIAGO');
INSERT INTO EMPLEADO VALUES(3, 'LILIAN', '6/22/1990', 'MANTENCIÓN', 'ALERCES 8698', 'VALPARAISO');
INSERT INTO EMPLEADO VALUES(4, 'ROSA', '4/12/1990', 'ADMINISTRACIÓN', 'CASAS 2423', 'TALCA');
INSERT INTO EMPLEADO VALUES(5, 'MARIA', '4/3/1990', 'DBA', 'PARQUE 1256', 'SANTIAGO');
INSERT INTO EMPLEADO VALUES(6, 'ALEJANDRA', '1/5/1990', 'ATENCIÓN CLIENTES', 'ALMOS 1223', 'LA SERENA');

//CONSULTAMOS LOS DATOS INGRESADOS

SELECT * FROM EMPLEADO;

//MODIFICAMOS AL EMPLEADO 2 EL CARGO A MANTENCIÓN

UPDATE EMPLEADO SET CARGO = 'MANTENCIÓN'
WHERE CODEMP = 2;

//MODIFICAMOS LA CIUDAD A TODOS LOS EMPLEADOS PARA QUE SEA SANTIAGO

UPDATE EMPLEADO SET CIUDAD = 'SANTIAGO';

//MODIFICAMOS LA FECHA DE NACIMIENTO DEL EMPLEADO 5 A 9/9/1980

UPDATE EMPLEADO SET FEC_NAC = '9/9/1980'
WHERE CODEMP = 5;

//DEJAMOS AL EMPLEADO 1 CON DIRECCIÓN NULA

UPDATE EMPLEADO SET DIRECCION = NULL
WHERE CODEMP = 1;

//MODIFICAMOS LA DIRECCION DEL EMPLEADO 6 A OESTE 5423

UPDATE EMPLEADO SET DIRECCION = 'OESTE 5423'
WHERE CODEMP = 6;

//CONSULTAMOS LA TABLA EMPLEADO PARA VER SU CAMBIO LUEGO DE LAS MODIFICACIONES REALIZADAS

SELECT * FROM EMPLEADO;

//ELIMINAMOS AL EMPLEADO 2

DELETE FROM EMPLEADO 
WHERE CODEMP = 2;

//CONSULTAMOS LA TABLA

SELECT * FROM EMPLEADO;

//ELIMINAMOS TODOS LOS REGISTROS DE LA TABLA EMPLEADO

DELETE FROM EMPLEADO;

//CONSULTAMOS NUEVAMENTE LA TABLA

SELECT * FROM EMPLEADO;

//no data found
//NO MOSTRARA NADA DADO QUE ELIMINAMOS TODOS LOS DATOS DE LA TABLA