//CREAR TABLA CLIENTE

CREATE TABLE CLIENTE(
IDENTIFICADOR INT,
NOMBRE VARCHAR2(20),
FEC_NAC DATE,
DIRECCION VARCHAR2(20),
COMUNA VARCHAR2(20)
);

//CREAR TABLE CELULAR

CREATE TABLE CELULAR(
CODCEL INT,
MARCA VARCHAR2(20),
MODELO VARCHAR2(20),
PRECIO INT
);

//CREAR TABLA PROPIETARIO

CREATE TABLE PROPIETARIO(
IDENTIFICADOR INT,
CODCEL INT,
COMPANIA VARCHAR2(20),
TELEFONO INT,
FEC_CONTRATO DATE
);

//AGREGAR LA PK A LA TABLA CLIENTE

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE_IDENTIFICADOR
PRIMARY KEY(IDENTIFICADOR);

//AGREGAR LA PK A LA TABLA CELULAR

ALTER TABLE CELULAR
ADD CONSTRAINT PK_CELULAR_CODCEL
PRIMARY KEY(CODCEL);

//AGREGAR LAS FK EN LA TABLA PROPIETARIO

ALTER TABLE PROPIETARIO
ADD CONSTRAINT FK_PROPIETARIO_IDENTIFICADOR
FOREIGN KEY(IDENTIFICADOR) REFERENCES
CLIENTE(IDENTIFICADOR);

ALTER TABLE PROPIETARIO
ADD CONSTRAINT FK_PROPIETARIO_CODCEL
FOREIGN KEY(CODCEL) REFERENCES
CELULAR(CODCEL);

//-------------------------------------------

//INSERTAR DATOS EN LAS TABLAS

INSERT INTO CLIENTE VALUES(1, 'PEDRO DÍAZ', '2/2/1998', 'MANZANO 1234', 'PEÑALOLEN');
INSERT INTO CLIENTE VALUES(2, 'ALEJANDRO PÉREZ', '11/2/1998', 'CASAS 1234', 'LA FLORIDA');
INSERT INTO CLIENTE VALUES(3, 'LILIAN ROJAS', '12/12/1999', 'PARCELAS 5635', 'PUDAHUEL');

INSERT INTO CELULAR VALUES(1, 'SAMSUNG', 'S9', 400000);
INSERT INTO CELULAR VALUES(2, 'SAMSUNG', 'S10', 500000);
INSERT INTO CELULAR VALUES(3, 'SAMSUNG', 'NOTE 10', 700000);
INSERT INTO CELULAR VALUES(4, 'APPLE', 'IPHONE 11 PRO', 1200000);

INSERT INTO PROPIETARIO VALUES(1, 1, 'CLARO', 12345678, '1/1/2020');
INSERT INTO PROPIETARIO VALUES(1, 4, 'ENTEL', 56556656, '2/2/2020');
INSERT INTO PROPIETARIO VALUES(2, 3, 'MOVISTAR', 45896523, '6/6/2020');
INSERT INTO PROPIETARIO VALUES(3, 2, 'CLARO', 56358745, '4/4/2020');

//------------------------------------------------------------------------

//MOSTRAR EL IDENTIFICADOR, NOMBRE DEL CLIENTE + LA COMPAÑIA A LA CUAL TIENEN CONTRATADA

SELECT CL.IDENTIFICADOR, CL.NOMBRE, PR.COMPANIA FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR;

//MOSTRAR LA COMPAÑIA Y LA CANTIDAD DE CLIENTES QUE TIENEN ASOCIADO CADA UNA DE ELLAS

SELECT PR.COMPANIA, COUNT(*) AS "CANTIDAD DE CLIENTES" FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR
GROUP BY PR.COMPANIA;

//MOSTRAR NOMBRE DEL CLIENTE + COMPAÑIA + MODELO DEL CELULAR

SELECT CL.NOMBRE, PR.COMPANIA, CE.MODELO FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR
INNER JOIN CELULAR CE ON PR.CODCEL = CE.CODCEL;

//MOSTRAR EL IDENTIFICADOR Y NOMBRE DEL CLIENTE QUE TIENEN CELULARES MARCA SAMSUNG DE LA LINEA S

SELECT DISTINCT(CL.IDENTIFICADOR), CL.NOMBRE FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR
INNER JOIN CELULAR CE ON PR.CODCEL = CE.CODCEL
WHERE MODELO LIKE 'S%';

//MOSTRAR LOS DATOS DE LOS CLIENTES QUE CONTRATARON PLANES EL AÑO 2020

SELECT DISTINCT(CL.IDENTIFICADOR), CL.NOMBRE, CL.FEC_NAC, CL.DIRECCION, CL.COMUNA FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR
WHERE EXTRACT(YEAR FROM FEC_CONTRATO) = 2020;

//MOSTRAR EL IDENTIFICADOR Y NOMBRE DE LOS CLIENTES QUE TIENEN CELULARES SOBRE 700000

SELECT DISTINCT(CL.IDENTIFICADOR), CL.NOMBRE FROM CLIENTE
CL INNER JOIN PROPIETARIO PR ON CL.IDENTIFICADOR = PR.IDENTIFICADOR
INNER JOIN CELULAR CE ON PR.CODCEL = CE.CODCEL
WHERE CE.PRECIO>= 700000;