
//CREAMOS UNA FUNCIÓN PARA SUMAR DOS NÚMEROS

CREATE OR REPLACE FUNCTION F_SUMAR(A NUMBER, B NUMBER)
RETURN NUMBER
IS
TOTAL NUMBER;
BEGIN
TOTAL:= A + B;
RETURN TOTAL;
END;

//PROBAMOS LA FUNCIÓN CREADA

SELECT F_SUMAR(2,4) FROM DUAL;

//CREAMOS UNA FUNCIÓN PARA CALCULAR EL PROMEDIO ENTRE DOS NÚMEROS

CREATE OR REPLACE FUNCTION F_PROMEDIO(A NUMBER, B NUMBER)
RETURN NUMBER
IS
TOTAL NUMBER;
BEGIN
TOTAL:=(A+B)/2;
RETURN TOTAL;
END;

//PROBAMOS LA FUNCIÓN CREADA

SELECT F_PROMEDIO(45,70) FROM DUAL;

//CREAMOS UNA FUNCIÓN LA CUAL NOS RETORNA SI UN NÚMERO ES PAR O IMPAR

CREATE OR REPLACE FUNCTION F_PAR_IMPAR(A NUMBER)
RETURN VARCHAR
IS
VALORRETORNADO VARCHAR(20);
BEGIN
IF MOD(A, 2) = 0 THEN
VALORRETORNADO:='PAR';
ELSE VALORRETORNADO:='IMPAR';
END IF;
RETURN VALORRETORNADO;
END;

//PROBAMOS LA FUNCIÓN CREADA

SELECT F_PAR_IMPAR(1532) FROM DUAL;

//CREAMOS UNA TABLA LLAMADA PRODUCTO

CREATE TABLE PRODUCTO(
ID NUMBER,
NOMBRE VARCHAR2(20),
PRECIO NUMBER
);

//INGRESAMOS DATOS EN LA TABLA

INSERT INTO PRODUCTO VALUES(1, 'COMPUTADOR', 800000);
INSERT INTO PRODUCTO VALUES(2, 'CELULAR', 400000);
INSERT INTO PRODUCTO VALUES(3, 'MOCHILA', 30000);

//CREAMOS UNA FUNCIÓN PARA SABER SI EL PRODUCTO ES CARO O BARATO

CREATE OR REPLACE FUNCTION F_PRODUCTO_CARO_BARATO(A NUMBER)
RETURN VARCHAR
IS
VALORRETORNADO VARCHAR(20);
BEGIN
IF A >=500000 THEN
VALORRETORNADO:='CARO';
ELSE VALORRETORNADO:='BARATO';
END IF;
RETURN VALORRETORNADO;
END;

//REALIZAMOS UN SELECT PARA CONSULTAR

SELECT ID, NOMBRE, PRECIO, F_PRODUCTO_CARO_BARATO(PRECIO) AS "CARO O BARATO" FROM PRODUCTO;

//AGREGAMOS UN NUEVO CAMPO A LA TABLA

ALTER TABLE PRODUCTO
ADD CARO_BARATO VARCHAR2(20);

//CONSULTAMOS LA TABLA

SELECT * FROM PRODUCTO;

//MODIFICAMOS LOS DATOS DE LA TABLA Y UTILIZAMOS LA FUNCIÓN F_PRODUCTO_CARO_BARATO

UPDATE PRODUCTO SET CARO_BARATO = F_PRODUCTO_CARO_BARATO(PRECIO);

//ELIMINAMOS LA FUNCIÓN F_PRODUCTO_CARO_BARATO

DROP FUNCTION F_PRODUCTO_CARO_BARATO;

//CREAMOS UNA FUNCIÓN PARA SUMAR TRES NÚMEROS

CREATE OR REPLACE FUNCTION F_SUMAR_3(A NUMBER, B NUMBER, C NUMBER)
RETURN NUMBER
IS
BEGIN
RETURN A + B + C;
END;

//PROBAMOS LA FUNCIÓN CREADA

SELECT F_SUMAR_3(2,2,2) FROM DUAL;

//ELIMINAMOS LA FUNCIÓN

DROP FUNCTION F_SUMAR_3;