// CREAR SECUENCIA LLAMADA SEC_EJEMPLO QUE EMPIEZA CON 1, INCREMENTA EN 1, VALOR MÍNIMO 1, VALOR MÁXIMO 100, CYCLE PARA QUE CUANDO FINALICE SE VUELVA A REPETIR, NOCYCLE PARA QUE FINALICE

CREATE SEQUENCE SEC_EJEMPLO 
START WITH 1 
INCREMENT BY 1 
MINVALUE 1 
MAXVALUE 100 
CYCLE;

SELECT SEC_EJEMPLO.NEXTVAL FROM DUAL; //MUESTRA EL PRÓXIMO VALOR DE LA SECUENCIA

SELECT SEC_EJEMPLO.CURRVAL FROM DUAL; //MUESTRA EL VALOR ACTUAL DE LA SECUENCIA

//ALTERAR SECUENCIA PARA QUE EL VALOR MÍNIMO SEA 10 Y EL AUMENTO SEA DE 2

ALTER SEQUENCE SEC_EJEMPLO
MINVALUE 10
INCREMENT BY 2;

//CONSULTA LAS SECUENCIAS QUE EXISTEN

SELECT * FROM ALL_OBJECTS
WHERE OBJECT_TYPE='SEQUENCE';

//CONSULTAR LA SECUENCIA CREADA

SELECT * FROM ALL_OBJECTS
WHERE OBJECT_NAME='SEC_EJEMPLO';

DROP SEQUENCE SEC_EJEMPLO; //BORRAR LA SECUENCIA