//CREAMOS LA TABLA HOTEL CON SUS CAMPOS Y TIPOS DE DATOS

CREATE TABLE HOTEL(
CODIGO INT,
NOMBRE VARCHAR2(20),
ESTRELLAS INT,
DIRECCION VARCHAR2(30),
PAIS VARCHAR2(20)
);

//CONSULTAMOS LA DESCRIPCIÓN DE LA TABLA RECIEN CREADA

DESC HOTEL;

//INSERTAMOS UN REGISTRO DE EJEMPLO

INSERT INTO HOTEL VALUES(1, 'HOTEL ABC', 5, 'LAS PARCELAS 11111', 'CHILE');

//CONSULTAMOS LOS DATOS EN LA TABLA HOTEL

SELECT * FROM HOTEL;

//CREAMOS LA TABLA ACTOR CON SUS CAMPOS Y TIPOS DE DATOS

CREATE TABLE ACTOR(
CODACT INT,
NOMBRE VARCHAR2(20),
CORREO VARCHAR2(20),
TELEFONO INT,
FECHA_NACIMIENTO DATE,
DIRECCION VARCHAR2(30),
CIUDAD VARCHAR2(20)
);

//CONSULTAMOS LA DESCRIPCIÓN DE LA TABLA RECIEN CREADA

DESC ACTOR;

//INSERTAMOS UN REGISTRO DE EJEMPLO

INSERT INTO ACTOR VALUES(1, 'JUAN PÉREZ', 'JUAN@GMAIL.COM', 12345678, '12/27/1990', 'LAS CASAS 654', 'SANTIAGO');

//CONSULTAMOS LOS DATOS EN LA TABLA ACTOR

SELECT * FROM ACTOR;
