SELECT ADD_MONTHS('10/18/2020', 2) FROM DUAL; //AGREGA MESES A LA FECHA INGRESADA (2)

SELECT LAST_DAY('10/18/2020') FROM DUAL; //ARROJA EL ÚLTIMO DÍA DEL MES

SELECT MONTHS_BETWEEN('10/18/2020', '1/1/1998') FROM DUAL; //CUENTA LOS MESES ENTRE DOS FECHAS

SELECT NEXT_DAY('10/18/2020', 'MONDAY') FROM DUAL; //MUESTRA LA FECHA DEL DÍA PRÓXIMO A LA INGRESADA (MONDAY)

SELECT CURRENT_DATE FROM DUAL; //FECHA DE LA ZONA

SELECT SYSDATE FROM DUAL; //FECHA DEL SERVIDOR ORACLE

SELECT CURRENT_TIMESTAMP FROM DUAL; //FECHA Y HORA DE LA ZONA

SELECT SYSTIMESTAMP FROM DUAL; //FECHA Y HORA DEL SERVIDOR ORACLE

SELECT EXTRACT(YEAR FROM SYSTIMESTAMP) FROM DUAL; //EXTRAE EL AÑO DEL SYSTIMESTAMP, PUEDE SER YEAR/MONTH/DAY/HOUR/MINUTE/SECOND

SELECT TO_DATE('18/10/2020', 'DD/MM/YYYY') FROM DUAL; //CONVIERTE LA CADENA EN A TIPO DATE

SELECT TO_CHAR('10/18/2020') FROM DUAL; //CONVIERTE EL TIPO DATE A CADENA DE CARACTERES