//CREAMOS LA TABLA CUENTA

CREATE TABLE CUENTA(
NRO INT,
RUT INT,
SALDO INT,
TIPO VARCHAR2(20)
);

//AGREGAMOS LA PK

ALTER TABLE CUENTA
ADD CONSTRAINT PK_CUENTA_NRO
PRIMARY KEY(NRO);

//INSERTAMOS DATOS EN LA TABLA CREADA

INSERT INTO CUENTA VALUES(0001, 1111, 500000, 'CUENTA CORRIENTE');
INSERT INTO CUENTA VALUES(0002, 2222, 602000, 'CUENTA DE AHORRO');

//CONSULTAMOS LOS DATOS INGRESADOS

SELECT * FROM CUENTA;

//CREAMOS UN PROCEDIMIENTO PARA AUMENTAR EN UN 10% EL SALDO DE UNA CUENTA, INGRESANDO EL NRO DE ESTA

CREATE PROCEDURE P_AUMENTO10(NRO_CUENTA IN NUMBER)
AS
BEGIN
UPDATE CUENTA SET SALDO = SALDO * 1.1
WHERE NRO = NRO_CUENTA;
END;

//EJECUTAMOS EL PROCEDIMIENTO

BEGIN
P_AUMENTO10(0001);
END;

//CONSULTAMOS LOS DATOS DE LA TABLA PARA COMPROBAR EL AUMENTO

SELECT * FROM CUENTA;

//CREAMOS UN PROCEDIMIENTO PARA AUMENTAR EL SALDO EN UN X PORCIENTO DE UNA CUENTA ESPECÍFICA 

CREATE PROCEDURE P_AUMENTO(NRO_CUENTA IN NUMBER, AUMENTO IN NUMBER)
AS
BEGIN
UPDATE CUENTA SET SALDO = SALDO + (SALDO*AUMENTO)/100
WHERE NRO = NRO_CUENTA;
END;

//CONSULTAMOS LOS DATOS ANTES DE EJECUTAR EL PROCEDIMIENTO
SELECT * FROM CUENTA;

//EJECUTAMOS EL PROCEDIMIENTO

BEGIN
P_AUMENTO(0002, 100);
END;

//CONSULTAMOS LA TABLA PARA VER EL CAMBIO QUE SE REALIZO

SELECT * FROM CUENTA;

//CREAREMOS UN PROCEDIMIENTO PARA QUE AL INSERTAR DATOS EN UNA TABLA ESTE TENGA VALORES POR DEFECTO

CREATE PROCEDURE P_INGRESAR_CUENTA(NRO_CUENTA IN NUMBER, RUT IN NUMBER, SALDO IN NUMBER DEFAULT 0, TIPO IN VARCHAR DEFAULT 'AHORRO')
AS
BEGIN
INSERT INTO CUENTA VALUES(NRO_CUENTA, RUT, SALDO, TIPO);
END;

//EJECUTAMOS EL PROCEDIMIENTO

BEGIN
P_INGRESAR_CUENTA(0003, 3333);
END;

//CONSULTAMOS LA TABLA CUENTA PARA VER LOS VALORES POR DEFECTO DE LOS CAMPOS NO INGRESADOS

SELECT * FROM CUENTA;

//MODIFICAMOS EL PROCEDURE P_AUMENTO10 PARA QUE EL PORCENTAJE DE ESTE SEA 20

CREATE OR REPLACE PROCEDURE P_AUMENTO10(NRO_CUENTA IN NUMBER)
AS
BEGIN
UPDATE CUENTA SET SALDO = SALDO * 1.2
WHERE NRO = NRO_CUENTA;
END;

//CONSULTAMOS LA TABLA CUENTA ANTES DE EJECUTAR EL PROCEDIMIENTO

SELECT * FROM CUENTA;

//EJECUTAMOS EL PROCEDIMIENTO

BEGIN
P_AUMENTO10(0001);
END;

//COMPROBAMOS QUE AUMENTO UN 20% EL SALDO DE LA CUENTA 0001

SELECT * FROM CUENTA;

//BORRAMOS EL PROCEDIMIENTO P_AUMENTO10

DROP PROCEDURE P_AUMENTO10;

//BORRAMOS EL PROCEDIMIENTO P_AUMENTO

DROP PROCEDURE P_AUMENTO;

//BORRAMOS EL PROCEDIMIENTO P_INGRESAR_CUENTA;

DROP PROCEDURE P_INGRESAR_CUENTA;
