//CREAMOS LA TABLA MASCOTA

CREATE TABLE MASCOTA(
CHIP INT,
NOMBRE VARCHAR2(20),
FEC_NAC DATE,
TIPO_MASCOTA VARCHAR2(20),
RAZA VARCHAR2(20)
);

//CREAMOS LA PK

ALTER TABLE MASCOTA
ADD CONSTRAINT PK_MASCOTA_CHIP
PRIMARY KEY(CHIP);

//INSERTAMOS DATOS EN LA TABLA MASCOTA

INSERT INTO MASCOTA VALUES(1111, 'JONNY', '1/1/2020', 'PERRO', 'CHIGUAGUA');
INSERT INTO MASCOTA VALUES(2222, 'ROCO', '2/2/2020', 'PERRO', 'CANE CORSO');
INSERT INTO MASCOTA VALUES(3333, 'PIRRU', '5/2/2018', 'GATO', 'PERSA');
INSERT INTO MASCOTA VALUES(4444, 'MISIFU', '2/4/2019', 'GATO', 'SPHYNX');
INSERT INTO MASCOTA VALUES(5555, 'MILOVAN', '3/1/2019', 'PERRO', 'CHIGUAGUA');
INSERT INTO MASCOTA VALUES(6666, 'CHIQUI', '7/7/2020', 'PERRO', 'BICHÓN MALTÉS');

//MOSTRAR LA CANTIDAD DE MASCOTA POR RAZA

SELECT RAZA, COUNT(*) AS CANTIDAD FROM MASCOTA
GROUP BY RAZA;

//MOSTRAR LA CANTIDAD DE GATOS REGISTRADOS

SELECT TIPO_MASCOTA, COUNT(*) FROM MASCOTA
WHERE TIPO_MASCOTA = 'GATO'
GROUP BY TIPO_MASCOTA;

//MOSTRAR LA CANTIDAD DE PERROS REGISTRADOS

SELECT TIPO_MASCOTA, COUNT(*) FROM MASCOTA
WHERE TIPO_MASCOTA = 'PERRO'
GROUP BY TIPO_MASCOTA;

//MOSTRAR LA CANTIDAD DE CHIGUAGUAS EXISTENTES

SELECT RAZA, COUNT(*) AS CANTIDAD FROM MASCOTA
WHERE RAZA = 'CHIGUAGUA'
GROUP BY RAZA;

//MOSTRAR LA CANTIDAD DE GATOS PERSA EXISTENTES

SELECT RAZA, COUNT(*) AS CANTIDAD FROM MASCOTA
WHERE RAZA = 'PERSA'
GROUP BY RAZA;

//MOSTRAR LA CANTIDAD DE GATOS SPHYNX Y PERROS CANE CORSO

SELECT RAZA, COUNT(*) AS CANTIDAD FROM MASCOTA
WHERE RAZA = 'PERSA' OR RAZA = 'CANE CORSO'
GROUP BY RAZA;

//MOSTRAR EL TIPO DE MASCOTA QUE TIENE MAS DE 2 EJEMPLARES

SELECT TIPO_MASCOTA, COUNT(*) AS CANTIDAD FROM MASCOTA
GROUP BY TIPO_MASCOTA
HAVING COUNT(*)>2;

//MOSTRAR LA RAZA DE MASCOTA QUE TIENE MENOS DE 2 EJEMPLARES

SELECT RAZA, COUNT(*) FROM MASCOTA
GROUP BY RAZA
HAVING COUNT(*)<2;